
package cl.clarochile.generatetokencudbws.facade;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GenerateTokenCUDBService", targetNamespace = "http://facade.generatetokencudbws.clarochile.cl", wsdlLocation = "file:/C:/Users/Daniela/AppData/Local/Temp/tempdir16201541143113192146.tmp/GenerateTokenCUDBService_1.wsdl")
public class GenerateTokenCUDBService
    extends Service
{

    private final static URL GENERATETOKENCUDBSERVICE_WSDL_LOCATION;
    private final static WebServiceException GENERATETOKENCUDBSERVICE_EXCEPTION;
    private final static QName GENERATETOKENCUDBSERVICE_QNAME = new QName("http://facade.generatetokencudbws.clarochile.cl", "GenerateTokenCUDBService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Daniela/AppData/Local/Temp/tempdir16201541143113192146.tmp/GenerateTokenCUDBService_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GENERATETOKENCUDBSERVICE_WSDL_LOCATION = url;
        GENERATETOKENCUDBSERVICE_EXCEPTION = e;
    }

    public GenerateTokenCUDBService() {
        super(__getWsdlLocation(), GENERATETOKENCUDBSERVICE_QNAME);
    }

    public GenerateTokenCUDBService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GENERATETOKENCUDBSERVICE_QNAME, features);
    }

    public GenerateTokenCUDBService(URL wsdlLocation) {
        super(wsdlLocation, GENERATETOKENCUDBSERVICE_QNAME);
    }

    public GenerateTokenCUDBService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GENERATETOKENCUDBSERVICE_QNAME, features);
    }

    public GenerateTokenCUDBService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GenerateTokenCUDBService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Generatetokencudbws
     */
    @WebEndpoint(name = "generatetokencudbws")
    public Generatetokencudbws getGeneratetokencudbws() {
        return super.getPort(new QName("http://facade.generatetokencudbws.clarochile.cl", "generatetokencudbws"), Generatetokencudbws.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Generatetokencudbws
     */
    @WebEndpoint(name = "generatetokencudbws")
    public Generatetokencudbws getGeneratetokencudbws(WebServiceFeature... features) {
        return super.getPort(new QName("http://facade.generatetokencudbws.clarochile.cl", "generatetokencudbws"), Generatetokencudbws.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GENERATETOKENCUDBSERVICE_EXCEPTION!= null) {
            throw GENERATETOKENCUDBSERVICE_EXCEPTION;
        }
        return GENERATETOKENCUDBSERVICE_WSDL_LOCATION;
    }

}
