
package com.ericsson.schemas.cai3g1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Cai3gFault", targetNamespace = "http://schemas.ericsson.com/cai3g1.2/")
public class Cai3GFaultException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private Cai3GFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Cai3GFaultException(String message, Cai3GFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Cai3GFaultException(String message, Cai3GFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.ericsson.schemas.cai3g1.Cai3GFault
     */
    public Cai3GFault getFaultInfo() {
        return faultInfo;
    }

}
